---
- name: S'assurer que Nginx est démarré
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deployer la page d'accueil Pro
  copy:
    dest: /var/www/html/index.html
    content: |
      <h1>Site En Production - Deployed by Ansible</h1>
      <p>Serveur : {{ ansible_hostname }}</p>
