---
- hosts: web_servers
  become: true 
  roles:
    - web_server

- hosts: load_balancer
  become: true
  roles:
    - load_balancer

- hosts: app_servers
  become: true
  roles:
    - app_server


- hosts: db_servers
  become: true
  roles:
    - db_server
